name: Bug Report (User/Farmer)
description: Report a bug in a released version of AgOpenGPS
title: "[Bug] "
labels: ["bug", "needs-triage", "user-reported"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! Please provide as much detail as possible to help us fix it.

  - type: input
    id: version
    attributes:
      label: AgOpenGPS Version
      description: Which version are you using? (Check Help > About in the application)
      placeholder: "e.g., v6.8.0, v7.0.1, or 'latest from GitHub'"
    validations:
      required: true

  - type: dropdown
    id: application
    attributes:
      label: Which Application?
      description: Which program is affected?
      options:
        - AgOpenGPS (main application)
        - AgIO (communication hub)
        - Both
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Open AgOpenGPS...
        2. Go to Settings...
        3. Click on...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware Setup
      description: What hardware are you using?
      options:
        - GPS receiver only
        - GPS + Section Control
        - GPS + Auto-steer
        - Full setup (GPS + Section Control + Auto-steer)
        - Simulator (no hardware)
        - Other
    validations:
      required: false

  - type: textarea
    id: hardware_details
    attributes:
      label: Hardware Details (if applicable)
      description: What hardware are you using?
      placeholder: |
        GPS receiver: (e.g., F9P, BNO085)
        Connection type: (e.g., USB, Ethernet, UDP)
        PCB board: (e.g., v4.1 Standard, v5.0)
        Auto-steer motor: (if using auto-steer)
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows 11
        - Windows 10
        - Windows 8/8.1
        - Windows 7
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Any error messages, crash dialogs, or log files
      placeholder: |
        Copy and paste any error messages you see.
        Log files can be found in the AgOpenGPS installation folder.
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, videos, field notes, configuration files, etc.
      placeholder: Add any other context that might help diagnose the issue
    validations:
      required: false