name: Bug Report (Development Branch)
description: Report a bug found in the develop branch
title: "[Dev Bug] "
labels: ["bug", "needs-triage", "dev-branch"]
body:
  - type: markdown
    attributes:
      value: |
        ## Development Branch Bug Report
        For bugs found in the `develop` branch or during development/testing.

  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Which branch is affected?
      options:
        - develop (main development)
        - feature branch
        - release candidate
    validations:
      required: true

  - type: input
    id: commit
    attributes:
      label: Commit Hash
      description: The specific commit where this bug was found (first 7-8 characters is fine)
      placeholder: "e.g., a1b2c3d or full hash"
    validations:
      required: true

  - type: input
    id: pr
    attributes:
      label: Related PR (if applicable)
      description: Link to the PR that may have introduced or is related to this bug
      placeholder: "#123 or https://github.com/AgOpenGPS-Official/AgOpenGPS/pull/123"
    validations:
      required: false

  - type: dropdown
    id: application
    attributes:
      label: Which Application?
      description: Which program is affected?
      options:
        - AgOpenGPS
        - AgIO
        - Both
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: What's wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Checkout commit a1b2c3d from develop
        2. Build solution in Visual Studio
        3. Run AgOpenGPS.exe
        4. Navigate to...
        5. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (crashes, data loss, blocks merge to master)
        - High (major functionality broken)
        - Medium (workaround available)
        - Low (minor issue, cosmetic)
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this work before in develop or master?
      options:
        - "Yes - this worked in a previous commit"
        - "No - new feature/code"
        - "Unknown"
    validations:
      required: true

  - type: input
    id: last_working
    attributes:
      label: Last Known Working Commit (if regression)
      description: If regression, what commit last worked correctly?
      placeholder: "e.g., b2c3d4e"
    validations:
      required: false

  - type: textarea
    id: code_location
    attributes:
      label: Affected Code/Files
      description: Which files or classes are affected?
      placeholder: |
        - FormGPS.cs line 456
        - clsContour.cs
        - Autosteer module
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Development Environment
      description: Build environment details
      placeholder: |
        - Visual Studio 2022 Community
        - Windows 11 Pro
        - .NET Framework 4.8
        - Testing with simulator / actual hardware
    validations:
      required: false

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Used (if applicable)
      description: Hardware setup used during testing
      placeholder: |
        - PCB: v4.1 Standard
        - GPS: F9P via USB
        - Section control board connected
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Stack Trace
      description: Paste relevant error messages, exceptions, or stack traces
      placeholder: Paste error logs here...
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, debugger output, related issues, potential fixes, etc.
      placeholder: Any additional information that might help solve this issue
    validations:
      required: false