name: Bug Report (Development Branch)
description: Report a bug found in the develop branch
title: "[Dev Bug] "
labels: ["bug", "needs-triage", "dev-branch"]
body:
  - type: markdown
    attributes:
      value: |
        ## Development Branch Bug Report
        For bugs found in the `develop` branch or during development/testing.

  - type: input
    id: branch_commit
    attributes:
      label: Branch/Commit
      description: Which branch or commit hash?
      placeholder: "e.g., develop, a1b2c3d, or PR #123"
    validations:
      required: false

  - type: dropdown
    id: application
    attributes:
      label: Which Application?
      description: Which program is affected?
      options:
        - AgOpenGPS
        - AgIO
        - Both
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: What's wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the issue
      placeholder: |
        1. Checkout develop branch
        2. Run AgOpenGPS
        3. Click/navigate to...
        4. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs Actual Behavior
      description: What should happen vs what actually happens?
      placeholder: |
        Expected: Should save field data
        Actual: Application crashes with NullReferenceException
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (crashes, data loss)
        - High (major feature broken)
        - Medium (minor issue)
        - Low (cosmetic)
    validations:
      required: false

  - type: textarea
    id: code_location
    attributes:
      label: Affected Code/Files (if known)
      description: Which files or classes are affected?
      placeholder: "e.g., FormGPS.cs line 456, CYouTurn.cs"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Stack Trace
      description: Paste relevant error messages, exceptions, or stack traces
      placeholder: Paste error logs here...
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, debugger output, related issues, potential fixes, etc.
      placeholder: Any additional information that might help solve this issue
    validations:
      required: false