name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop
      - release/*

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./SourceCode/AgOpenGPS.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  # Path to the output folder
  PUBLISH_DIR: ./AgOpenGPS

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.3.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v4.1.0
      with:
        updateProjectFiles: true

    - name: Install dependencies
      run: dotnet restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: dotnet build --no-restore ${{env.SOLUTION_FILE_PATH}}

    - name: Test
      run: dotnet test --no-restore --no-build ${{env.SOLUTION_FILE_PATH}}

    - name: Publish
      run: dotnet publish --no-restore --configuration ${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AgOpenGPS
        path: ${{env.PUBLISH_DIR}}
